// Import the Java Runtime Environment
#import "JreEmulation.h"

// Import OpenWIG Java Classes
#import "Action.h"
#import "BackgroundRunner.h"
#import "BaseLib.h"
#import "Cartridge.h"
#import "CartridgeFile.h"
#import "Container.h"
#import "CoroutineLib.h"
#import "Engine.h"
#import "EventTable.h"
#import "FileHandle.h"
#import "JavaFunction.h"
#import "LocationService.h"
#import "LuaCallFrame.h"
#import "LuaClosure.h"
#import "LuaException.h"
#import "LuaPrototype.h"
#import "LuaState.h"
#import "LuaTable.h"
#import "LuaTableImpl.h"
#import "LuaThread.h"
#import "MathLib.h"
#import "Media.h"
#import "OsLib.h"
#import "Player.h"
#import "Savegame.h"
#import "SeekableFile.h"
#import "Serializable.h"
#import "StringLib.h"
#import "TableLib.h"
#import "Task.h"
#import "Thing.h"
#import "Timer.h"
#import "UI.h"
#import "UpValue.h"
#import "WherigoLib.h"
#import "Zone.h"
#import "ZonePoint.h"
#import "WSeekableFile.h"
#import "WSaveFile.h"

// Import Core Java Libraries
#import "java/io/File.h"
#import "java/io/FileOutputStream.h"
#import "java/io/DataInputStream.h"
#import "java/io/DataOutputStream.h"
#import "java/util/Vector.h"
